# Installs MKL-linked versions of NumPy and some useful dev tools.
# You don't need to use this if you're not a Conda user. Note you will
# need to install ONE OF {modelfree,aprl}/requirements.txt after this.
name: aprl
dependencies:
    - python=3.6
    - mkl=2019.1  # speed up NumPy on Intel CPUs
    - numpy>=1.15
    - pip>=18.0
    - ipython
    - jupyter
    - qtconsole
    - pip:
        - -r requirements-build.txt
        - -r requirements.txt
